### ISSUE TITLE
Initial elbo is NA

### ISSUE THREAD

**Issue by Puriney** [kieranrcampbell/clonealign#4]
Hi,
I was wondering any hints on why I came across the error "Initial elbo is NA"?

Occasionally, I met across the error. They were gone if I removed features with either NAs or zeros in all cells. But sometimes they still exist, so I was wondering why? Could it also because the tf$session did not run at all?

https://github.com/kieranrcampbell/clonealign/blob/289b9a255bc1a15524483a27b318426751d53fea/R/inference-tflow.R#L369

**Comment by kieranrcampbell** [comment]
I have seen the error before but I can't quite remember why - I suspect it's a filtering issue. Can you double check:

1. The input data are non-negative integer counts
2. That you filter out any genes with copy number zero
3. All copy numbers are non-negative (silly I know but would cause the mistake)

I will make sure that clonealign implements these checks too. 

On another note, I'm working on a pipeline for clonealign for our datasets here at BC Cancer - https://github.com/kieranrcampbell/clonealign-pipeline. Currently no documentation, but the current "best practice" for running is at
https://github.com/kieranrcampbell/clonealign-pipeline/blob/master/pipeline/run_clonealign.Rmd
in terms of filtering based on expression variance, etc - hope that helps

**Comment by Puriney** [comment]
Your suggestions help. Sounds like checking the more corner case of input matrices. Thanks again for prompt replies.

**Comment by heathergeiger** [comment]
I am getting this error for a matrix where all of the conditions you suggested to check were not a problem. I have 936 genes and 3 clones. Of these, I have 487 with copy number 3 in clone C, copy number 2 in clones A and B. Then another 449 with copy number 2 in clone B, copy number 3 in clones A and C.

I ran preprocess_for_clonealign using standard parameters to get down to these 936 genes. Also leads to filtering from 12,810 cells down to 10,564.

I had another run of the same RNA data, but also including a fourth clone D for the gene x clone matrix. This run also included an additional 149 genes with copy number 2 in clones A, B, and C, but with copy number 3 in clone D. This run ran through without the "initial elbo is NA" error. It was only when I tried to exclude clone D (and also exclude the 149 genes) that I started getting an error.

**Comment by markutz556** [comment]
I have the same issue as @heathergeiger. I appreciate any ideas. Thanks!

**Comment by kieranrcampbell** [comment]
Very strange....can you print:

```r
summary(as.vector(gene_expression_data))
summary(as.vector(copy_number_data))
```

?

**Comment by markutz556** [comment]
Hi @kieranrcampbell,

For one dataset, I found there was no copy number change between clones, which I think causes this error.

For another dataset, here is the stats (1927 cells, 10 genes, and 3 clones):

summary(as.vector(gene_expression_data))
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.0000  0.0000  0.0000  0.1674  0.0000  5.0000 

 summary(as.vector(copy_number_data))
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  1.000   1.000   2.000   1.667   2.000   2.000 

Another naive question: how Clonealign handle the situation where only one clone exists in the data?

Thank you

**Comment by kieranrcampbell** [comment]
Hi @markutz556 

If only one clone exists in the data then all cells should theoretically belong to it so there is no need to do any assignment.

Thanks

Kieran
