### ISSUE TITLE
Solve the problem in installing clonealign

### ISSUE THREAD

**Issue by XQBai** [kieranrcampbell/clonealign#9]
**Hello,  I have installed the "tensorflow" and "clonealign" packages as shown the guidance. However, there always an error as below:**

Constructing tensorflow graph
Error in py_get_attr_impl(x, name, silent) : 
AttributeError: module 'tensorflow' has no attribute 'reset_default_graph'

**Then, I saw the setting of python in r-tensorflow,** 

`>reticulate::py_config()`
python:         /Users/Amssbaixiangqi/.virtualenvs/r-tensorflow/bin/python
libpython:      /Users/Amssbaixiangqi/miniconda2/envs/r-tensorflow/lib/libpython3.6m.dylib
pythonhome:     /Users/Amssbaixiangqi/miniconda2/envs/r-tensorflow:/Users/Amssbaixiangqi/miniconda2/envs/r-tensorflow
version:        3.6.8 |Anaconda, Inc.| (default, Dec 29 2018, 19:04:46)  [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
numpy:          /Users/Amssbaixiangqi/.virtualenvs/r-tensorflow/lib/python3.6/site-packages/numpy
numpy_version:  1.16.4
tensorflow:     /Users/Amssbaixiangqi/.virtualenvs/r-tensorflow/lib/python3.6/site-packages/tensorflow
python versions found: 
 /Users/Amssbaixiangqi/.virtualenvs/r-tensorflow/bin/python
 /Users/Amssbaixiangqi/miniconda2/envs/r-tensorflow/bin/python
 /anaconda/envs/r-tensorflow/bin/python
 /usr/bin/python
 /usr/local/bin/python
 /usr/local/bin/python3
 /Users/Amssbaixiangqi/miniconda2/envs/pyclone/bin/python
 /anaconda/envs/python27/bin/python
 /anaconda/envs/python35/bin/python
 /Users/Amssbaixiangqi/miniconda2/bin/python
 /Users/Amssbaixiangqi/server413/bin/python

**It is noted that another python are used in virtual environment '/Users/Amssbaixiangqi/.virtualenvs/r-tensorflow/bin/python'.  Thus I removed all paths about the virtual environment. After that, clonealign is successfully installed.** 

`> Sys.getenv()`
__CF_USER_TEXT_ENCODING          0x1F5:0x19:0x34
__KMP_REGISTERED_LIB_4892        0x1018c0c20-cafed01c-libomp.dylib
__KMP_REGISTERED_LIB_6593        0x1018c0c20-cafe7519-libomp.dylib
Apple_PubSub_Socket_Render       /private/tmp/com.apple.launchd.8G2juMc7bT/Render
CLICOLOR_FORCE                   1
DISPLAY                          /private/tmp/com.apple.launchd.sN5ofUkFip/org.macosforge.xquartz:0
DYLD_FALLBACK_LIBRARY_PATH       /Library/Frameworks/R.framework/Resources/lib:/Library/Frameworks/R.framework/Resources/lib:/Users/Amssbaixiangqi/lib:/usr/local/lib:/usr/lib:::/lib:/Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home/jre/lib/server:::/Library/Frameworks/R.framework/Resources/lib:/Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home/jre/lib/server
EDITOR                           vi
GIT_ASKPASS                      rpostback-askpass
GITHUB_PAT                       34bba114f6b4e43b786ff2c41a82ca69c5dbe0ce
HOME                             /Users/Amssbaixiangqi
LANG                             zh_CN.UTF-8
LC_CTYPE                         zh_CN.UTF-8
LN_S                             ln -s
LOGNAME                          Amssbaixiangqi
MAKE                             make
PAGER                            /usr/bin/less
PATH                             /Users/Amssbaixiangqi/.virtualenvs/r-tensorflow/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/Library/TeX/texbin
R_BROWSER                        /usr/bin/open
R_BZIPCMD                        /usr/bin/bzip2
R_DOC_DIR                        /Library/Frameworks/R.framework/Resources/doc
R_GZIPCMD                        /usr/bin/gzip
R_HOME                           /Library/Frameworks/R.framework/Resources
R_INCLUDE_DIR                    /Library/Frameworks/R.framework/Resources/include
R_LIBS_SITE                      
R_LIBS_USER                      ~/Library/R/3.6/library
R_PAPERSIZE                      a4
R_PDFVIEWER                      /usr/bin/open
R_PLATFORM                       x86_64-apple-darwin15.6.0
R_PRINTCMD                       lpr
R_QPDF                           /Library/Frameworks/R.framework/Resources/bin/qpdf
R_RD4PDF                         times,inconsolata,hyper
R_SESSION_INITIALIZED            PID=6593:NAME="reticulate"
R_SESSION_TMPDIR                 /var/folders/md/rqyl44w50b5cpm9wtsh19q200000gn/T//RtmpLYCtf2
R_SHARE_DIR                      /Library/Frameworks/R.framework/Resources/share
R_STRIP_SHARED_LIB               strip -x
R_STRIP_STATIC_LIB               strip -S
R_SYSTEM_ABI                     osx,gcc,gxx,gfortran,gfortran
R_TEXI2DVICMD                    /usr/local/bin/texi2dvi
R_UNZIPCMD                       /usr/bin/unzip
R_ZIPCMD                         /usr/bin/zip
RETICULATE_REQUIRED_MODULE       tensorflow
RMARKDOWN_MATHJAX_PATH           /Applications/RStudio.app/Contents/Resources/resources/mathjax-26
RS_RPOSTBACK_PATH                /Applications/RStudio.app/Contents/MacOS/rpostback
RS_SHARED_SECRET                 dbc39f44-b589-45e4-921b-10943a4f8c63
RSTUDIO                          1
RSTUDIO_CONSOLE_COLOR            256
RSTUDIO_CONSOLE_WIDTH            111
RSTUDIO_PANDOC                   /Applications/RStudio.app/Contents/MacOS/pandoc
RSTUDIO_SESSION_PORT             25163
RSTUDIO_USER_IDENTITY            Amssbaixiangqi
RSTUDIO_WINUTILS                 bin/winutils
SED                              /usr/bin/sed
SHELL                            /bin/bash
SSH_ASKPASS                      rpostback-askpass
SSH_AUTH_SOCK                    /private/tmp/com.apple.launchd.3tDs9H4Bj5/Listeners
TAR                              /usr/bin/tar
TERM                             xterm-256color
TMPDIR                           /var/folders/md/rqyl44w50b5cpm9wtsh19q200000gn/T/
USER                             Amssbaixiangqi
VIRTUAL_ENV                      /Users/Amssbaixiangqi/.virtualenvs/r-tensorflow
XPC_FLAGS                        0x0
XPC_SERVICE_NAME                 0

```
> Sys.unsetenv('VIRTUAL_ENV')
> Sys.unsetenv('PATH')
> Sys.unsetenv('RETICULATE_REQUIRED_MODULE')
> Sys.getenv()

```
`> reticulate::py_config()`
python:         /Users/Amssbaixiangqi/miniconda2/envs/r-tensorflow/bin/python
libpython:      /Users/Amssbaixiangqi/miniconda2/envs/r-tensorflow/lib/libpython3.6m.dylib
pythonhome:     /Users/Amssbaixiangqi/miniconda2/envs/r-tensorflow:/Users/Amssbaixiangqi/miniconda2/envs/r-tensorflow
version:        3.6.8 |Anaconda, Inc.| (default, Dec 29 2018, 19:04:46)  [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
numpy:          /Users/Amssbaixiangqi/miniconda2/envs/r-tensorflow/lib/python3.6/site-packages/numpy
numpy_version:  1.16.4
tensorflow:     /Users/Amssbaixiangqi/miniconda2/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow
python versions found: 
 /Users/Amssbaixiangqi/miniconda2/envs/r-tensorflow/bin/python
 /anaconda/envs/r-tensorflow/bin/python
 /usr/bin/python
 /usr/local/bin/python
 /usr/local/bin/python3
 /Users/Amssbaixiangqi/miniconda2/envs/pyclone/bin/python
 /anaconda/envs/python27/bin/python
 /anaconda/envs/python35/bin/python
 /Users/Amssbaixiangqi/miniconda2/bin/python
 /Users/Amssbaixiangqi/server413/bin/python

**Comment by kieranrcampbell** [comment]
Hi @XQBai 

Great - thanks for posting and resolving!
